# Generated by Django 3.2.8 on 2024-07-10 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_management', '0002_fridgespace_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridgeitem',
            name='space',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fridge_management.fridgespace'),
            preserve_default=False,
        ),
    ]
