# Generated by Django 3.2.8 on 2024-07-10 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_management', '0003_fridgeitem_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgespace',
            name='share_key',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
